#screen -mdS Count_5 fish -c "python3 RL_Trainer.py --gpu --name Count_5 --n 5 --env Maze-4-v1 --count --bonus-after-epsilon"
#screen -mdS Count_10 fish -c "python3 RL_Trainer.py --gpu --name Count_10 --n 10 --env Maze-4-v1 --count --bonus-after-epsilon"
#screen -mdS Count_20 fish -c "python3 RL_Trainer.py --gpu --name Count_20 --n 20 --env Maze-4-v1 --count --bonus-after-epsilon"
screen -mdS DQN_10 fish -c "python3 RL_Trainer.py --gpu --name DQN_10 --n 10 --env Maze-4-v1"
screen -mdS Count_5 fish -c "python3 RL_Trainer.py --gpu --name Count_5 --n 5 --env Maze-4-v1 --count"
screen -mdS Count_10 fish -c "python3 RL_Trainer.py --gpu --name Count_10 --n 10 --env Maze-4-v1 --count"
screen -mdS Count_1 fish -c "python3 RL_Trainer.py --gpu --name Count_1 --n 1 --env Maze-4-v1 --count"
